### ISSUE TITLE
truncate table error in Postgres

### ISSUE THREAD

**Issue by vznncv** [Clarivate-LSPS/tMDataLoader#28]
The sql/postgres/permissions.sql doesn't give truncating right to user "tm_cz" and tm_etl.jar fails when the data is loaded:
![pic](https://cloud.githubusercontent.com/assets/14029493/13112232/fb662206-d59a-11e5-9544-5a534764cb7f.png)
Also error was when expression data is loaded, but I haven't screenshot. The error was in the procedure sql/postgres/procedures/I2B2_PROCESS_MRNA_DATA.sql at row 156, because "(select distinct platform from lt_src_mrna_subj_samp_map) " can return more then one row.

**Comment by mirasrael** [comment]
You should prefer to use tm_dataloader user instead of tm_cz user. I updated README to reflect this point.
For your problem with expression data it is most probably problem with input data and I can't help with the issue without concrete sample.
