### ISSUE TITLE
Where is the log

### ISSUE THREAD

**Issue by Kabenla** [Clarivate-LSPS/tMDataLoader#33]
When an ETL job fails, the is a Debug statement that suggests we look at the log.  
"Job Failed: See error log for details"

Where is the log located?

**Comment by jeremy-singer** [comment]
Kabenla,

Sorry I didn’t answer more promptly, I didn’t see your email until now.

There should be a logs directory under the place where you are running the ETL, and in there is a log file.
If you have not defined a logs directory, you should do so.  I’m not sure that the process will write a log if it doesn’t find such a directory.

Thanks.

Jeremy Singer
Senior Developer
Thompson Reuters Life Sciences

mobile: 857.243.0694
email: Jeremy.Singer@thomsonreuters.com
skype: Jeremy.B.Singer

**Comment by Kabenla** [comment]
Thanks for your response,

When you say "under the place where you are running the ETL” are you referring to the path specified in ~/.tm_etl/YOUR_ETL_DIRECTORY?

Kabenla

**Comment by Kabenla** [comment]
Hi Jeremy, 
Sorry what i meant to was are you referring to the path specified in ~/.tm_etl/Config.groovy by the dataDir variable?

Kabenla Armah

**Comment by jeremy-singer** [comment]
No, I think it actually gets put in a directory called “logs” under the directory where you invoke the tm_etl.jar file.

[3:31] 
as I mentioned, you need a logs directory there.

[3:33] 
on my instance, it is in /u01/transmart/logs
