### ISSUE TITLE
Halt in clinical data loader

### ISSUE THREAD

**Issue by abhishekdxt** [Clarivate-LSPS/tMDataLoader#37]
Hi,

I have ran into a unique issue. The jar file runs without any problem until 'Replace pipes with comma in data_label' and it then takes a long pause. 

Last week I managed to load some big clinical data using your loader. The whole process took just under 3 hours but today when I tried to load a fairly simple data file (2970 x 29) the loader was surprisingly very slow.

May I know if the jar file fetch any script from your side/server before executing the statements in i2b2_load_clinical_data procedure? If yes, then it may explain the slow loading as I am using the same jar.

Thanks.

**Comment by mirasrael** [comment]
Hi @abhishekdxt. No, it isn't. All required information already present in tMDataLoader package (code & sql scripts). Can you recheck you have ran all SQL scripts for your database. If problem is still present, then you can obfuscate your data files, retry to be sure problem still present and send them to us so we will able to reproduce and fix the problem.

**Comment by mirasrael** [comment]
Closed because no additional information was provided and wasn't able to reproduce.
