### ISSUE TITLE
Loading Metadata

### ISSUE THREAD

**Issue by Kabenla** [Clarivate-LSPS/tMDataLoader#40]
Hi I am trying to load metadata with a study and currently stuck.  Here are the sequence of events
1) I followed the instructions in the wiki and the first error that I got was an error telling me that the relation lt_src_study_metadata did not exist.
2) I added a table called lt_src_study_metadata to the tm_cz schema and made tm_dataloader the owner
3) I got an error which gave me a long list of missing columns in the table
4) using this error message I logged into the database and run the following command to add the columns.  I more or less guessed the types for each of the columns
ALTER TABLE lt_src_study_metadata
ADD STUDY_ID varchar(25),
ADD TITLE varchar(25),
ADD DESCRIPTION varchar(250),
ADD DESIGN varchar(25),
ADD START_DATE date,
ADD COMPLETION_DATE date,
ADD PRIMARY_INVESTIGATOR varchar(25),
ADD CONTACT_FIELD varchar(25),
ADD STATUS varchar(25),
ADD OVERALL_DESIGN varchar(50),
ADD INSTITUTION varchar(100),
ADD COUNTRY varchar(50),
ADD BIOMARKER_TYPE varchar(50),
ADD TARGET varchar(50),
ADD ACCESS_TYPE varchar(50),
ADD STUDY_OWNER varchar(50),
ADD STUDY_PHASE varchar(100),
ADD BLINDING_PROCEDURE varchar(100),
ADD STUDYTYPE varchar(50),
ADD DURATION_OF_STUDY_WEEKS numeric,
ADD NUMBER_OF_PATIENTS numeric,
ADD NUMBER_OF_SITES numeric,
ADD ROUTE_OF_ADMINISTRATION varchar(250),
ADD DOSING_REGIMEN varchar(250),
ADD GROUP_ASSIGNMENT varchar(50),
ADD TYPE_OF_CONTROL varchar(50),
ADD PRIMARY_END_POINTS varchar(50),
ADD SECONDARY_END_POINTS varchar(50),
ADD INCLUSION_CRITERIA varchar(100),
ADD EXCLUSION_CRITERIA varchar(100),
ADD SUBJECTS varchar(100),
ADD GENDER_RESTRICTION_MFB varchar(100),
ADD MIN_AGE numeric,
ADD MAX_AGE numeric,
ADD SECONDARY_IDS varchar(100),
ADD DEVELOPMENT_PARTNER varchar(100),
ADD GEO_PLATFORM varchar(100),
ADD MAIN_FINDINGS varchar(100),
ADD SEARCH_AREA varchar(100),
ADD COMPOUND varchar(100),
ADD DISEASE varchar(100),
ADD PUBMED_IDS varchar(100),
ADD ORGANISM varchar(100);

Now the loading gives me the following error
05/26 05:19:21 MSG Run procedures: I2B2_LOAD_STUDY_METADATA
05/26 05:19:21 DBG -- Starting i2b2_load_study_metadata [Done / 0 recs / 0.0s]
05/26 05:19:21 DBG -- Job Failed: See error log for details [FAIL / 1 recs / 0.017816s]
05/26 05:19:21 ERR function is_date(date, unknown) does not exist / null / null
05/26 05:19:21 ERR Procedure completed with errors!

**Comment by nboukharov** [comment]
Currently not supported by tranSMART
