### ISSUE TITLE
Category_cd in VCF Mapping file

### ISSUE THREAD

**Issue by Kabenla** [Clarivate-LSPS/tMDataLoader#54]
Hi, is it possible to specify the path to VCF data in the file tree.  In other words, can we put a category_cd column in the VCF mapping file?

Kabenla

**Comment by mirasrael** [comment]
Hi @Kabenla. No, it is not possible currently to customize path for VCF data.

**Comment by mirasrael** [comment]
Hi again @Kabenla. Sorry for missleading you. Actually you can add CATEGORY_CD column:
```
# STUDY_ID: Gse0
# STUDY_TITLE: Test Study
# GENOME_BUILD: hg36
SUBJECT_ID	SAMPLE_CD    CATEGORY_CD
Subject_0	VCF_TST001   VCFData+SNP+Something
Subject_1	VCF_TST002   VCFData+SNP+Something Else
```

**Comment by xuatiknc** [comment]
Also you can always move any node inside the study using the `-m` option:
```
java -jar tm_etl.jar -m '\Private Studies\My Study\VCF\' -m '\Private Studies\My Study\Something\Else\'
```

**Comment by Kabenla** [comment]
Thank you guys so much for the information!!

Kabenla
