### ISSUE TITLE
authentication failed with postgres procedures.sql

### ISSUE THREAD

**Issue by kforner** [Clarivate-LSPS/tMDataLoader#61]
Hi,

In a fresh new installation of transmart eTRIKS v4.0 (16.1) using https://github.com/dennyverbeeck/transmart-docker, I'm trying to setup the DB for use with tMDataLoader 1.2.4-116.

I could execute the 2 first postgresql scripts without any problem, but I get an error with the 3rd one:
```
$ psql -d transmart -U tm_dataloader -f procedures.sql
psql: FATAL:  Peer authentication failed for user "tm_dataloader"
```
I tried giving the tm_dataloader as a password as indicated in the README:
```
$ psql -d transmart -W -U tm_dataloader -f procedures.sql
Password for user tm_dataloader: 
# then typing: tm_dataloader
psql: FATAL:  Peer authentication failed for user "tm_dataloader"
```

What should I do ? 
Thanks.

**Comment by xuatiknc** [comment]
Hi,

try adding `-h 127.0.0.1` option.

**Comment by kforner** [comment]
great, it works !
Could you please tell me why the -h is need for  tm_dataloader but not for postgres ?

**Comment by mirasrael** [comment]
@kforner Because `postgresql` authentication enabled on OS level, but for non-system users you should use host authentication. By default Postgres uses OS authentication, but when you set a host then it switches to host authentication.

**Comment by kforner** [comment]
ok, thanks a lot.

**Comment by xuatiknc** [comment]
You may want to read documentation here: https://www.postgresql.org/docs/current/static/auth-pg-hba-conf.html
