### ISSUE TITLE
Making studies in Private Studies Folder secure

### ISSUE THREAD

**Issue by hangphan** [Clarivate-LSPS/tMDataLoader#65]
I tried to use  
>java -jar tm_etl.jar --secure-study '\Private Studies\CHI0497\' 

to set my private study CHI0497 to a secure object but when I tried to look at the Study List in my admin console in my web browser's transmart instance, I can't find the secureObject. Has anything happened at all? How do I set my study private using the web browser API? 

Thanks,
Hang

**Comment by xuatiknc** [comment]
Hi,

if you want to secure your study you need to re-load it with `--secure-study ` option. You can't secure study that has been already loaded.

**Comment by hangphan** [comment]
Thanks, I'll give it a try. 

However, is there a way to make a study that has not been loaded using the secure-study option to become a secure Object? I looked at the documentary of tranSMART and it seems that after loading a study, if I choose to create new study in the admin console, giving it the unique ID EXP:STUDYID then it would make secureObject. I tried to follow that instruction but it didn't seem to work. Do you have any idea or experience?

Thanks
Hang

**Comment by hangphan** [comment]
It worked. Thanks a lot. Do you have an answer to my other query ? Thanks
Hang

**Comment by xuatiknc** [comment]
Hi,

> is there a way to make a study that has not been loaded using the secure-study option to become a secure Object?

well, you can do that manually in the database. We did not implement this feature in tMDataLoader. From my personal experience I can say that users usually do not forget to use `--secure-study` option, but when they do they often find some other issues as well and fixing those would require re-loading study anyway.

> Do you have any idea or experience?

No. tMDataLoader does everything that is needed to load a study, so I have never used that part of admin console.
