### ISSUE TITLE
Confusing documentation about UPDATE merge mode

### ISSUE THREAD

**Issue by Kabenla** [Clarivate-LSPS/tMDataLoader#67]
The first line in the Update merge mode says "all clinical data for patients in the existing, previously loaded study will be removed and new data for these patients will be loaded".  The last line says "Data for subjects not included in the UPDATE data set will not be affected"

I am assuming that the last line means if a previously loaded subject was not included in the data files that are being updated, then that users data is not affected.  But how can that be if all the data for the patients in the existing previously loaded data has been removed?

Finally, how is UPDATE faster than REPLACE, if all the clinical data is removed

**Comment by xuatiknc** [comment]
Hi, I've changed the wording a little bit. Please let me know if that still did not clarify the issue.

Basically the difference is the following: suppose you've loaded a study that has 2 patients (Alice and Bob) with body temperatures 97.9F and 98.6F and heart rates 81 and 85 respectively. Now you noticed that you made a mistake: Alice's temperature actually was 98.1F and you want to fix it. If you do not use any `MERGE_MODE` (which is equivalent to `REPLACE`) then you need to delete all data and load the entire study again just to fix that one number. With `MERGE_MODE` you can only load the data you want to be updated. So you've created a data file which only contains the correct temperature value for Alice. If you use `UPDATE` mode it will delete all data for Alice and insert new temperature for her while Bob's data remains intact. If you use `UPDATE_VARIABLE` mode it will only delete and insert temperature values for Alice and everything else will be intact. I.e. with `UPDATE` you need to load *all* data for specific patient(s) and with `UPDATE_VARIABLE` you only need to load *changed* data for those patient(s).

**Comment by Kabenla** [comment]
Thanks so much Vadim,

This really clears things up for me.  Thanks for also updating the Wiki.

Kabenla
