### ISSUE TITLE
transmart version

### ISSUE THREAD

**Issue by aurelBZH** [Clarivate-LSPS/tMDataLoader#69]
Hi,
thanks for tMDataloader,
I use tMDataloader with transmart 16.3 and i'm wondering with which version of transmart tMDataloader is working? For example if i upgrade to transmart 17.1 or 19 (which is comming soon) is the tMDataloader will continue to work?
Thanks 
Aurélien Béliard
Bioinformatician 
i3 lab

**Comment by xuatiknc** [comment]
Hi,
there is a separate branch for 17.1. We tested it extensively but to the best of my knowledge it has never seen a real life usage.
We are currently working on version 19 support. It should be available in the master branch around the time tranSMART 19 is released.

**Comment by aurelBZH** [comment]
thanks a lot for your response
