### ISSUE TITLE
Problem setting up DB for tMDataLoader

### ISSUE THREAD

**Issue by kforner** [Clarivate-LSPS/tMDataLoader#7]
Hello,

I tried to follow the instructions to install the ETL for our local transmart installation running the transmart.war.1.2.2.e.fg-fix version, with a Postgres database created using the HEAD of https://github.com/transmart/transmart-data.git.

After 

```
git clone https://github.com/eugene-rakhmatulin/transmartApp-DB.git
git checkout post_GPL1.1.0_fixes
cd transmartApp-DB/postgresql_wGEO
```

When I execute:
psql -d transmart -f post_1.1.0_update.sql

I get:

```
...
CREATE FUNCTION
CREATE FUNCTION
psql:etl/functions/I2B2_BACKOUT_TRIAL.sql:242: ERROR:  cannot change return type of existing function
```

I then uncommented the DROP FUNCTION line in https://github.com/eugene-rakhmatulin/transmartApp-DB/blob/post_GPL1.1.0_fixes/postgresql_wGEO/etl/functions/I2B2_BACKOUT_TRIAL.sql#L3
but then I get:

```
...
CREATE FUNCTION
psql:etl/functions/median.sql:24: ERROR:  function "median" already exists with same argument types
```

What should I do ?

**Comment by mirasrael** [comment]
For version 1.2 you can ignore instructions for post_GPL1.1.0_fixes (they only related to 1.1 version). Please, notice that supported version was moved to https://github.com/ThomsonReuters-LSPS/tMDataLoader and you can find updated instructions following the link.

**Comment by kforner** [comment]
Thanks. There are other issues, I'll raise them in the new repository.
