### ISSUE TITLE
SNP data upload

### ISSUE THREAD

**Issue by kforner** [Clarivate-LSPS/tMDataLoader#8]
In the tutorial v1.5, it is mentioned that genotype calls can be downloaded using a calls text file.
In v2.1, I see no mention of SNP data...

So my question is: is-it possible, useful, recommended to upload a whole GWAS genotype data ?
Thanks

**Comment by mirasrael** [comment]
Hi, @kforner. We didn't find how to use uploaded SNP data in latest Transmart version. For tMDataLoader SNP upload only useful part is upload to expression data tables - copy number loaded as expression value (in parallel with upload to SNP specific tables). So you are able to apply analysis to  uploaded SNP data, but it only works with copy numbers and no way I know to see calls in interface.
